security:
  access_control:
    -
      path: ^/admin
      roles: ROLE_ADMIN
  encoders:
    App\Entity\User: bcrypt
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: ~
      form_login:
        always_use_default_target_path: true
        check_path: login
        default_target_path: admin_api
        login_path: login
      logout:
        path:   /logout
        target: /
      http_basic: ~
      provider: authentication_admin
    secured_area:
      form_login:
        csrf_token_generator: security.csrf.token_manager
  providers:
    authentication_admin:
      entity:
        class: App\Entity\User
        property: username
            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
